apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-sql-instance-pv
  labels:
    disk: system
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: storage
    path: "/srv/exports/volumes/sql-instance-1" 